apiVersion: apps/v1
kind: Deployment
metadata:
  name: diet-deployment
  namespace: ctn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diet-app
  template:
    metadata:
      labels:
        app: diet-app
    spec:
      containers:
      - name: diet-container
        image: ayeshactn/diet:1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"